### PR TITLE
Milestone 5: CRUD Operations for Star Destroyer Enemies

### PR DESCRIPTION
**Pull request by willkotheimer**
This is our 5th milestone

## Description

- Adds Create, Update, Read and delete operations for enemies
- Adds Styles
- Edits READ ME

## Related Issue

https://github.com/nss-evening-cohort-13/star-destroyer-dashboard-star-destroyer-dashboard/issues/39

## Motivation and Context

Completes 5th Milestone

## How Can This Be Tested?

git fetch origin development
git checkout development
npm start

[https://star-destroyer-a0766.web.app](https://star-destroyer-a0766.web.app)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by brownabs** [comment]
I need the site link

**Comment by willkotheimer** [comment]
https://star-destroyer-a0766.web.app

**Comment by brownabs** [comment]
I am seeing some changes that need to be made. Can you create a separate pull request for the readMe and I will approve?

**Comment by brownabs** [comment]
Give me a couple minutes and I will review the bugs, and you all can create bug fix tickets. Was this tested before submitting a PR?

**Comment by brownabs** [comment]
When trying to add an enemy, if I do not fill out all fields, it does not throw me an error. 
The edit button is not working for all the cards. When I click on Princess Leia, I do not see an edit form.

**Comment by willkotheimer** [comment]
We didn't see any bugs. What do you mean by a separate PR for the Readme. It's already merged, and has been PR'd by Jordan.

**Comment by brownabs** [comment]
Sorry separate milestone so I can approve it being merged into main

**Comment by brownabs** [comment]
> We didn't see any bugs. What do you mean by a separate PR for the Readme. It's already merged, and has been PR'd by Jordan.

^^ see above

**Comment by HunterJuneau** [comment]
We're not seeing those bugs, are you on the deployed site?

**Pull request closed without merging**
